const fs = require('node:fs/promises'),
  math = require('mathjs'),
  fp = require('./fp'),
  IccMaxDOM = require('./iccmax-dom'),
  { decode_ndin, encode_ndin } = require('./icc-private-tags'),
  equal = require('deep-equal'),
  BRADFORD_TRASNFORM = [
    [0.8951, 0.2664, -0.1614],
    [-0.7502, 1.7135, 0.0367],
    [0.0389, -0.0685, 1.0296]
  ],
  BRADFORD_INVERSE_TRANSFORM = math.inv(BRADFORD_TRASNFORM),
  LMS_CAT02_TRANSFORM = [
    [0.7328, 0.4296, -0.1624],
    [-0.7036, 1.6975, 0.0061],
    [0.003, 0.0136, 0.9834]
  ],
  LMS_CAT02_INVERSE_TRANSFORM = math.inv(LMS_CAT02_TRANSFORM),
  // based on Display P3.icc
  D65_TO_D50_TRANSFORM = [
    [1.047882080078, 0.022918701172, -0.050201416016],
    [0.029586791992, 0.990478515625, -0.017059326172],
    [0.009231567383, 0.015075683594, 0.751678466797]
  ],
  // CIE
  D65_WHITE = [0.95047, 1, 1.08883],
  D50_WHITE = [0.96422, 1, 0.82521],
  // based on Display P3 mediaWhitePoint
  D50_WHITE_1 = [0.96418762207, 1, 0.824890136719],
  // based on Display P3 PCSIluminant
  D50_WHITE_2 = [0.964202880859, 1, 0.824905395508]

function xy2xyz(xy, normalize = false, s15f16int = false) {
  const xyz = [xy[0], xy[1], (s15f16int ? 0x10000 : 1) - xy[0] - xy[1]]
  return normalize ? xyz_normalize(xyz) : xyz
}

function xyz_normalize(xyz) {
  return [xyz[0] / xyz[1], 1, xyz[2] / xyz[1]]
}

// Comparison verification value
function validate_s15f16(r) {
  const ui = fp.toS15F16Int32(r)
  return fp.fromS15F16Int32(ui)
}

function create_chromatic_adaption(transform, w_xyz_src, w_xyz_dst) {
  const w_lms_src = math.multiply(transform, w_xyz_src),
    w_lms_dst = math.multiply(transform, w_xyz_dst),
    von_kries_transform = [
      [w_lms_dst[0] / w_lms_src[0], 0, 0],
      [0, w_lms_dst[1] / w_lms_src[1], 0],
      [0, 0, w_lms_dst[2] / w_lms_src[2]]
    ]
  return math.multiply(math.inv(transform), von_kries_transform, transform)
}

function apply_chromatic_adaption(transform, c_xyz_src, w_xyz_dst) {
  const chad = create_chromatic_adaption(transform, c_xyz_src.w, w_xyz_dst)
  return {
    w: w_xyz_dst,
    r: math.multiply(chad, c_xyz_src.r),
    g: math.multiply(chad, c_xyz_src.g),
    b: math.multiply(chad, c_xyz_src.b),
    chad
  }
}
function simulate_macos_icc_genaration(ndin, icc_chromacity, icc_pcs_white) {
  const // normalize base Y
    w = xy2xyz(ndin.white, true, true),
    r = xy2xyz(ndin.red, true, true),
    g = xy2xyz(ndin.green, true, true),
    b = xy2xyz(ndin.blue, true, true),
    // r, g, b luminance ratio
    lr = math.multiply(math.inv(math.transpose([r, g, b])), w),
    c_xyz_native = {
      w,
      r: math.multiply(r, lr[0]),
      g: math.multiply(g, lr[1]),
      b: math.multiply(b, lr[2])
    },
    c_xyz_d50_bradford = apply_chromatic_adaption(BRADFORD_TRASNFORM, c_xyz_native, icc_pcs_white),
    c_xyz_d50_cat02 = apply_chromatic_adaption(LMS_CAT02_TRANSFORM, c_xyz_native, D50_WHITE),
    sum = (c) => math.add(c.r, c.g, c.b)

  console.log('icc chromacity', icc_chromacity)
  console.log('\nicc PCS iluminant', icc_pcs_white)

  // I think this is correct
  // the mediaWhitePoint is exactly same as value generated by macos
  console.log('\nnative', c_xyz_native, 'rgb sum', sum(c_xyz_native))

  // rgb is closest to the value generated by macos,
  // but I don't understand why mediaWhitePoint is not D50
  // and the chromaticAdaptionTag is not present
  console.log('\nD50 bradford', c_xyz_d50_bradford, 'rgb sum', sum(c_xyz_d50_bradford))

  // It’s worth trying the V4 profile
  console.log('\nD50 CAT02', c_xyz_d50_cat02, 'rgb sum', sum(c_xyz_d50_cat02))
  return
}

async function main() {
  const displays = ['AW3225QF DP', 'DELL S3221QS', 'Color LCD']
  for (const d of displays) {
    const icc = await IccMaxDOM.fromXmlFile(`${__dirname}/../data/${d} macOS Generated.xml`),
      icc_chromacity = icc.selectDisplayChromacity(),
      icc_pcs_white = icc.selectHeader().PCSIlluminant,
      ndin = decode_ndin(icc.selectPrivateTagData('ndin'), true)
    simulate_macos_icc_genaration(ndin, icc_chromacity, icc_pcs_white)
  }
}

main()
  .then(() => {})
  .catch((err) => {
    console.error('Error:', err)
  })
